2025-02-04 16:36:35.156 +11:00 [INF] Now listening on: https://localhost:7007
2025-02-04 16:36:35.189 +11:00 [INF] Now listening on: http://localhost:5100
2025-02-04 16:36:35.256 +11:00 [INF] Application started. Press Ctrl+C to shut down.
2025-02-04 16:36:35.257 +11:00 [INF] Hosting environment: Development
2025-02-04 16:36:35.259 +11:00 [INF] Content root path: D:\Projects\BookStoreApp\BookStoreApp.API
2025-02-04 16:37:21.006 +11:00 [INF] Made call to Weather Endpoint
2025-02-04 16:37:21.062 +11:00 [ERR] Fatal Error Occurred
System.Exception: This is our logging test exception
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in D:\Projects\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 28
2025-02-04 16:37:33.728 +11:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: This is our logging test exception
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in D:\Projects\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 28
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-02-04 16:54:48.858 +11:00 [INF] Now listening on: https://localhost:7007
2025-02-04 16:54:48.886 +11:00 [INF] Now listening on: http://localhost:5100
2025-02-04 16:54:49.030 +11:00 [INF] Application started. Press Ctrl+C to shut down.
2025-02-04 16:54:49.031 +11:00 [INF] Hosting environment: Development
2025-02-04 16:54:49.032 +11:00 [INF] Content root path: D:\Projects\BookStoreApp\BookStoreApp.API
2025-02-04 16:58:02.979 +11:00 [INF] Made call to Weather Endpoint
2025-02-04 16:58:03.015 +11:00 [ERR] Fatal Error Occurred
System.Exception: This is our logging test exception
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in D:\Projects\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 28
2025-02-04 16:58:07.643 +11:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: This is our logging test exception
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in D:\Projects\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 28
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-02-04 17:00:02.962 +11:00 [INF] Now listening on: https://localhost:7007
2025-02-04 17:00:02.989 +11:00 [INF] Now listening on: http://localhost:5100
2025-02-04 17:00:03.114 +11:00 [INF] Application started. Press Ctrl+C to shut down.
2025-02-04 17:00:03.115 +11:00 [INF] Hosting environment: Development
2025-02-04 17:00:03.117 +11:00 [INF] Content root path: D:\Projects\BookStoreApp\BookStoreApp.API
2025-02-04 17:00:09.596 +11:00 [INF] Made call to Weather Endpoint
2025-02-04 17:00:09.629 +11:00 [ERR] Fatal Error Occurred
System.Exception: This is our logging test exception
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in D:\Projects\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 28
2025-02-04 17:00:11.663 +11:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: This is our logging test exception
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in D:\Projects\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 28
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-02-04 17:03:44.544 +11:00 [INF] Now listening on: https://localhost:7007
2025-02-04 17:03:44.569 +11:00 [INF] Now listening on: http://localhost:5100
2025-02-04 17:03:44.664 +11:00 [INF] Application started. Press Ctrl+C to shut down.
2025-02-04 17:03:44.666 +11:00 [INF] Hosting environment: Development
2025-02-04 17:03:44.667 +11:00 [INF] Content root path: D:\Projects\BookStoreApp\BookStoreApp.API
2025-02-04 17:03:49.843 +11:00 [INF] Made call to Weather Endpoint
2025-02-04 17:03:49.877 +11:00 [ERR] Fatal Error Occurred
System.Exception: This is our logging test exception
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in D:\Projects\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 28
2025-02-04 17:03:51.767 +11:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: This is our logging test exception
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in D:\Projects\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 28
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
